export default [
    { path: '/dashboard', component: require('./components/Dashboard.vue').default },
    { path: '/userdetails', component: require('./components/Userdetails.vue').default },
    { path: '/subsplan', component: require('./components/metadata/SubscriptionPlan.vue').default },
    { path: '/paymentmode', component: require('./components/metadata/PaymentMode.vue').default },
    { path: '/vehtype', component: require('./components/metadata/VehicleType.vue').default },
    { path: '/vcidetails', component: require('./components/VciDetails.vue').default },
    { path: '/subscription', component: require('./components/Subscription.vue').default },
    { path: '/vehfunc', component: require('./components/metadata/VehicleFunction.vue').default },
    { path: '/ecudetails', component: require('./components/EciDetails.vue').default },
    { path: '/vehicledetails', component: require('./components/VehicleDetail.vue').default },
    { path: '/livedata', component: require('./components/LiveData.vue').default },
    { path: '/writedata', component: require('./components/WriteData.vue').default },
    { path: '/dtcdata', component: require('./components/DtcData.vue').default },
    { path: '/iodata', component: require('./components/IoData.vue').default },
    { path: '/routinedata', component: require('./components/RoutineData.vue').default },
    { path: '/apkmgmt', component: require('./components/ApkManagement.vue').default },
    { path: '/sold', component: require('./components/SoldProduct.vue').default },
    { path: '/unsold', component: require('./components/UnsoldProduct.vue').default },
    { path: '/employee', component: require('./components/Employee.vue').default },
    { path: '/role', component: require('./components/Role.vue').default },
    { path: '/complaints', component: require('./components/Complaints.vue').default },
    { path: '/hexfile', component: require('./components/Hexfile.vue').default },
    { path: '/ecuflash', component: require('./components/EcuFlashReport.vue').default },
    { path: '/healthteststructure', component: require('./components/HealthTestStructure.vue').default },
    { path: '/addhealthteststructure', component: require('./components/addHealthTestStructure.vue').default },
    { path: '/updateHealthTestStructure/:id', component: require('./components/UpdateHealthTestStructure.vue').default },
    { path: '/language', component: require('./components/Language.vue').default },

    { path: '/member/members', component: require('./components/member/member.vue').default },
    { path: '/member/viewprofiledata', component: require('./components/member/viewprofiledata.vue').default },
    { path: '/notfound', component: require('./components/NotFound.vue').default },
    { path: '*', component: require('./components/NotFound.vue').default }
];